config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root "home#index"

  resources :documents
  get '/d/:share_token', to: 'documents#public_show', as: 'public_document'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  before_create :generate_share_token

  private

  def generate_share_token
    self.share_token = SecureRandom.hex(5)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :documents, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :authenticate_user!, except: [:public_show]
  before_action :set_document, only: [:destroy, :show]

  def index
    @documents = current_user.documents
  end

  def show
  end

  def new
    @document = Document.new
  end

  def create
    @document = current_user.documents.build(document_params)

    if @document.save
      redirect_to documents_path, notice: "File uploaded successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @document.destroy
    redirect_to documents_path, notice: "Document deleted successfully."
  end

  def public_show
    @document = Document.find_by!(share_token: params[:share_token])
    # render a view that allows public download
  end

  private

  def set_document
    @document = current_user.documents.find(params[:id])
  end

  def document_params
    params.require(:document).permit(:title, :description, :file)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!, only: [:index]
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/create.html.erb
<h1>Documents#create</h1>
<p>Find me in app/views/documents/create.html.erb</p>

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/index.html.erb
<%= link_to "Add New Document", new_document_path, class: "btn btn-primary" %>

<% if @documents.present? %>
  <h2>My Documents</h2>

  <% @documents.each do |doc| %>
    <p>
      <%= doc.title %> - 
      <%= link_to "Delete", document_path(doc), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %> |
      <%= link_to "Share", public_document_url(doc.share_token), target: "_blank" %>
    </p>
  <% end %>
<% else %>
  <p>No documents found.</p>
  <%= link_to "Add New Document", new_document_path, class: "btn btn-primary" %>
<% end %>

app/views/documents/new.html.erb
<h1>Documents#new</h1>
<%= form_with model: @document, local: true do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %><br>

  <%= form.label :description %>
  <%= form.text_area :description %><br>

  <%= form.label :file %>
  <%= form.file_field :file %><br>

  <%= form.submit "Upload" %>
<% end %>

app/views/documents/public_show.html.erb
<h2><%= @document.title %></h2>
<p><%= @document.description %></p>

<% if @document.file.attached? %>
  <p>
    <%= link_to "Download File", rails_blob_path(@document.file, disposition: "attachment") %>
  </p>
<% end %>

app/views/documents/show.html.erb
<h1>Documents#show</h1>
<p>Find me in app/views/documents/show.html.erb</p>

app/views/home/index.html.erb
<p>Welcome, <%= current_user.email %></p>
<%= link_to " Click to see all the documents", documents_path, class: "btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Ek Store" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, data: { turbo_method: :delete } %>
    <% end %>


    <%= yield %>
  </body>
</html>